<h2 class="table_top_title" id="tile_work">Плиточные работы</h2>





<h3 class="table_variant_title">Демонтажные работы</h3>
<table>
    <thead>
    <tr>
        <td class="column_1">№</td>
        <td class="column_2"  >Наименование работ</td>
        <td class="column_3"  >Ед.изм.</td>
        <td class="column_4"  >Стоимость работ (руб)*</td>
    </tr>
    </thead>
    <tbody>
        <tr></tr>
        <tr>
            <td>1</td>
            <td>Демонтаж напольной плитки</td>
            <td>кв.м.</td>
            <td>75</td>
        </tr>
        <tr>
            <td>2</td>
            <td>Удаление остатков старого клея/раствора со стен</td>
            <td>кв.м.</td>
            <td>100</td>
        </tr>
        <tr>
            <td>3</td>
            <td>Демонтаж плитки со стен</td>
            <td>кв.м.</td>
            <td>75</td>
        </tr>
        <tr>
            <td>4</td>
            <td>Удаление остатков старого клея/раствора со стен</td>
            <td>кв.м.</td>
            <td>100</td>
        </tr>
    </tbody>
</table>




<h3 class="table_variant_title">Монтажные работы</h3>
<table>
    <thead>
        <tr>
            <td class="column_1">№</td>
            <td class="column_2"  >Наименование работ</td>
            <td class="column_3"  >Ед.изм.</td>
            <td class="column_4"  >Стоимость работ (руб)*</td>
        </tr>
    </thead>
    <tbody>
        <tr class="tr_table">
            <td colspan="4" class="table_title"><h2>Полы</h2></td>
        </tr>
        <tr>
            <td class="column_1" >1</td>
            <td class="column_2" >Укладка керамической плитки по подготовленному полу</td>
            <td class="column_3" >кв.м.</td>
            <td class="column_4 price" >500</td>
        </tr>
        <tr>
            <td class="column_1" >2</td>
            <td class="column_2" >Укладка керамической плитки с заданным рисунком по подготовленному полу</td>
            <td class="column_3" >кв.м.</td>
            <td class="column_4 price" >от 700</td>
        </tr>
        <tr>
            <td class="column_1" >3</td>
            <td class="column_2" >Устройство плинтуса из плитки</td>
            <td class="column_3" >м.п.</td>
            <td class="column_4 price" >200</td>
        </tr>
        <tr>
            <td class="column_1" >4</td>
            <td class="column_2" >Затирка плитки / мозаики</td>
            <td class="column_3" >кв.м.</td>
            <td class="column_4 price" >100</td>
        </tr>
        <tr>
            <td class="column_1" >5</td>
            <td class="column_2" >Затирка плитки / мозаики (разными цветами)</td>
            <td class="column_3" >кв.м.</td>
            <td class="column_4 price" >150</td>
        </tr>
        <tr>
            <td class="column_1" >6</td>
            <td class="column_2" >Облицовка пола мозаикой</td>
            <td class="column_3" >кв.м.</td>
            <td class="column_4 price" >от 1000</td>
        </tr>
        <tr>
            <td class="column_1" >7</td>
            <td class="column_2" >Облицовка плиткой ступеней </td>
            <td class="column_3" >м.п.</td>
            <td class="column_4 price" >от 700</td>
        </tr>
        <tr>
            <td class="column_1" >8</td>
            <td class="column_2" >Укладка керамической плитки по подготовленному полу по диагонали</td>
            <td class="column_3" >кв.м.</td>
            <td class="column_4 price" >700</td>
        </tr>
        <tr class="tr_table">
            <td colspan="4" class="table_title"><h2>Стены</h2></td>
        </tr>
        <tr>
            <td class="column_1" >1</td>
            <td class="column_2" >Облицовка стен керамической плиткой по подготовленной поверхности</td>
            <td class="column_3" >кв.м.</td>
            <td class="column_4 price" >500</td>
        </tr>
        <tr>
            <td class="column_1" >2</td>
            <td class="column_2" >Укладка плитки по диагонали</td>
            <td class="column_3" >кв.м.</td>
            <td class="column_4 price" >700</td>
        </tr>
        <tr>
            <td class="column_1" >3</td>
            <td class="column_2" >Устройство бордюра из плитки</td>
            <td class="column_3" >п.м.</td>
            <td class="column_4 price" >200</td>
        </tr>
        <tr>
            <td class="column_1" >4</td>
            <td class="column_2" >Облицовка стен керамической плиткой с заданным рисунком</td>
            <td class="column_3" >кв.м.</td>
            <td class="column_4 price" >от 700</td>
        </tr>
        <tr>
            <td class="column_1" >5</td>
            <td class="column_2" >Облицовка плиткой 10см*10см</td>
            <td class="column_3" >кв.м.</td>
            <td class="column_4 price" >800</td>
        </tr>
        <tr>
            <td class="column_1" >6</td>
            <td class="column_2" >Облицовка плиткой (мозаикой)</td>
            <td class="column_3" >кв.м.</td>
            <td class="column_4 price" >от 1000</td>
        </tr>
        <tr>
            <td class="column_1" >7</td>
            <td class="column_2" >Облицовка бордюра из мозаики</td>
            <td class="column_3" >м.п.</td>
            <td class="column_4 price" >400</td>
        </tr>
        <tr>
            <td class="column_1" >8</td>
            <td class="column_2" >Установка угловых окончаний из ПВХ</td>
            <td class="column_3" >м.п.</td>
            <td class="column_4 price" >100</td>
        </tr>
        <tr>
            <td class="column_1" >9</td>
            <td class="column_2" >Затирка плитки / мозаики</td>
            <td class="column_3" >кв.м.</td>
            <td class="column_4 price" >100</td>
        </tr>
        <tr>
            <td class="column_1" >10</td>
            <td class="column_2" >Затирка плитки / млзаики (разными цветами)</td>
            <td class="column_3" >кв.м.</td>
            <td class="column_4 price" >150</td>
        </tr>
        <tr>
            <td class="column_1" >11</td>
            <td class="column_2" >Облицовка стен декоративным камнем</td>
            <td class="column_3" >кв.м.</td>
            <td class="column_4 price" >от 800</td>
        </tr>
        <tr>
            <td class="column_1" >12</td>
            <td class="column_2" >Затирка швов декоративного камня</td>
            <td class="column_3" >м.п.</td>
            <td class="column_4 price" >150</td>
        </tr>
        <tr>
            <td class="column_1" >13</td>
            <td class="column_2" >Устройство технологических отверстий</td>
            <td class="column_3" >шт.</td>
            <td class="column_4 price" >150</td>
        </tr>
        <tr>
            <td class="column_1" >14</td>
            <td class="column_2" >Устройство технологических отверстий в керамграните</td>
            <td class="column_3" >шт.</td>
            <td class="column_4 price" >200</td>
        </tr>
        <tr>
            <td class="column_1" >15</td>
            <td class="column_2" >Рез плитки (радиус)</td>
            <td class="column_3" >п.м.</td>
            <td class="column_4 price" >от 500</td>
        </tr>
        <tr>
            <td class="column_1" >16</td>
            <td class="column_2" >Рез плитки (45*)</td>
            <td class="column_3" >м.п.</td>
            <td class="column_4 price" >от 500</td>
        </tr>
    </tbody>
</table>
<h2 class="table_top_title" id="plumbing_work">Сантехнические работы</h2>
<h3 class="table_variant_title">Демонтажные работы</h3>
<table>
    <thead>
        <tr>
            <td class="column_1">№</td>
            <td class="column_2"  >Наименование работ</td>
            <td class="column_3"  >Ед.изм.</td>
            <td class="column_4 price"  >Стоимость работ (руб)*</td>
        </tr>
    </thead>
    <tbody>
        <tr></tr>
        <tr>
            <td >1</td>
            <td >Демонтаж труб водопровода</td>
            <td >п.м.</td>
            <td >50</td>
        </tr>
        <tr>
            <td >2</td>
            <td >Демонтаж трубы канализации (чугун)</td>
            <td >п.м.</td>
            <td >150</td>
        </tr>
        <tr>
            <td >3</td>
            <td >Демонтаж трубы канализации (пластик)</td>
            <td >п.м.</td>
            <td >100</td>
        </tr>
        <tr>
            <td >4</td>
            <td >Демонтаж смесителя</td>
            <td >шт.</td>
            <td >100</td>
        </tr>
        <tr>
            <td >5</td>
            <td >Демонтаж унитаза</td>
            <td >шт.</td>
            <td >300</td>
        </tr>
        <tr>
            <td >6</td>
            <td >Демонтаж мойки, умывальника</td>
            <td >шт.</td>
            <td >300</td>
        </tr>
        <tr>
            <td >7</td>
            <td >Демонтаж ванной ( чугунной)</td>
            <td >шт.</td>
            <td >500</td>
        </tr>
        <tr>
            <td >8</td>
            <td >Демонтаж ванной (стальной)</td>
            <td >шт.</td>
            <td >350</td>
        </tr>
        <tr>
            <td >9</td>
            <td >Демонтаж ванной ( акриловой)</td>
            <td >шт.</td>
            <td >350</td>
        </tr>
        <tr>
            <td >10</td>
            <td >Демонтаж радиаторов отопления</td>
            <td >шт.</td>
            <td >200</td>
        </tr>
        <tr>
            <td >11</td>
            <td >Демонтаж полотенце сушки</td>
            <td >шт.</td>
            <td >200</td>
        </tr>
        <tr>
            <td >12</td>
            <td >Демонтаж шарового крана</td>
            <td >шт.</td>
            <td >50</td>
        </tr>
        <tr>
            <td >13</td>
            <td >Демонтаж душевой кабины</td>
            <td >шт.</td>
            <td >1000</td>
        </tr>
    </tbody>
</table>
<h3 class="table_variant_title">Монтажные работы</h3>
<table>
    <thead>
    <tr>
        <td class="column_1">№</td>
        <td class="column_2"  >Наименование работ</td>
        <td class="column_3"  >Ед.изм.</td>
        <td class="column_4 price"  >Стоимость работ (руб)*</td>
    </tr>
    </thead>
    <tbody>
    <tr></tr>
        <tr>
            <td >1</td>
            <td >Монтаж трубы (полипропилен)</td>
            <td >п.м.</td>
            <td >200</td>
        </tr>
        <tr>
            <td >2</td>
            <td >Штробление пола под трубы отопления и водоснабжения (в зависисмоти от глубины и ширины)</td>
            <td >п.м.</td>
            <td >от 150</td>
        </tr>
        <tr>
            <td >3</td>
            <td >Штробление стены под трубы отопления и водоснабжения (в зависисмоти от глубины и ширины)</td>
            <td >п.м.</td>
            <td >от 200</td>
        </tr>
        <tr>
            <td >4</td>
            <td >Штробление пола под трубы канализации</td>
            <td >п.м.</td>
            <td >от 250</td>
        </tr>
        <tr>
            <td >5</td>
            <td >Монтаж поворотных элементов канализации d 50/d100</td>
            <td >шт.</td>
            <td >100</td>
        </tr>
        <tr>
            <td >6</td>
            <td >Заделка штробы труб водопровода, канализации в стене и полах</td>
            <td >п.м.</td>
            <td >100</td>
        </tr>
        <tr>
            <td >7</td>
            <td >Монтаж трубы канализационной</td>
            <td >п.м.</td>
            <td >150</td>
        </tr>
        <tr>
            <td >8</td>
            <td >Монтаж шарового крана, фильтра, клапана</td>
            <td >шт.</td>
            <td >от 100</td>
        </tr>
        <tr>
            <td >9</td>
            <td >Монтаж смесителя</td>
            <td >шт.</td>
            <td >от 500</td>
        </tr>
        <tr>
            <td >10</td>
            <td >Монтаж унитаза, биде</td>
            <td >шт.</td>
            <td >от 1500</td>
        </tr>
        <tr>
            <td >11</td>
            <td >Монтаж инсталляции под унитаз, биде, раковину</td>
            <td >шт.</td>
            <td >от 1500</td>
        </tr>
        <tr>
            <td >12</td>
            <td >Монтаж унитаза, биде, раковины инсталлируемой</td>
            <td >шт.</td>
            <td >от 1000</td>
        </tr>
        <tr>
            <td >13</td>
            <td >Монтаж мойки / тюльпана</td>
            <td >шт.</td>
            <td >от 700</td>
        </tr>
        <tr>
            <td >14</td>
            <td >Монтаж тумбы с раковиной</td>
            <td >шт.</td>
            <td >от 1500</td>
        </tr>
        <tr>
            <td >15</td>
            <td >Монтаж ванны (стальной)</td>
            <td >шт.</td>
            <td >от 2000</td>
        </tr>
        <tr>
            <td >16</td>
            <td >Монтаж ванны (чугунной / акриловой)</td>
            <td >шт.</td>
            <td >от 3000</td>
        </tr>
        <tr>
            <td >17</td>
            <td >Монтаж радиатора отопления</td>
            <td >шт.</td>
            <td >от 1000</td>
        </tr>
        <tr>
            <td >18</td>
            <td >Технологически необходимый монтаж-демонтаж радиатора</td>
            <td >шт.</td>
            <td >500</td>
        </tr>
        <tr>
            <td >19</td>
            <td >Монтаж термоголовки на радиатор отопления</td>
            <td >шт.</td>
            <td >500</td>
        </tr>
        <tr>
            <td >20</td>
            <td >Монтаж душевой кабины</td>
            <td >шт.</td>
            <td >от 3000</td>
        </tr>
        <tr>
            <td >21</td>
            <td >Монтаж счётчика воды</td>
            <td >шт.</td>
            <td >1000</td>
        </tr>
        <tr>
            <td >22</td>
            <td >Монтаж теплых водяных полов (без укладки фольгоизола и полиэтилена)</td>
            <td >шт.</td>
            <td >500</td>
        </tr>
        <tr>
            <td >23</td>
            <td >Монтаж коллектора</td>
            <td >шт.</td>
            <td >500</td>
        </tr>
        <tr>
            <td >24</td>
            <td >Монтаж пресс соединения</td>
            <td >шт.</td>
            <td >250</td>
        </tr>
        <tr>
            <td >25</td>
            <td >Наращивание, скручивание коллектора</td>
            <td >шт.</td>
            <td >300</td>
        </tr>
        <tr>
            <td >26</td>
            <td >Подключение труб к коллектору</td>
            <td >шт.</td>
            <td >100</td>
        </tr>
        <tr>
            <td >27</td>
            <td >Установка котла</td>
            <td >шт.</td>
            <td >от 1500</td>
        </tr>
        <tr>
            <td >28</td>
            <td >Обвязка котла</td>
            <td >шт.</td>
            <td >от 3000</td>
        </tr>
        <tr>
            <td >29</td>
            <td >Монтаж полотенцесушки</td>
            <td >шт.</td>
            <td >от 1000</td>
        </tr>
    </tbody>
</table>
<h2 class="table_top_title" id="footer_work">Потолочные работы</h2>
<h3 class="table_variant_title">Демонтажные работы</h3>
<table>
    <thead>
        <tr>
            <td class="column_1">№</td>
            <td class="column_2"  >Наименование работ</td>
            <td class="column_3"  >Ед.изм.</td>
            <td class="column_4 price"  >Стоимость работ (руб)*</td>
        </tr>
    </thead>
    <tbody>
        <tr></tr>
        <tr>
            <td >1</td>
            <td >Демонтаж подвесных потолков (реечных / кассетных) </td>
            <td >кв.м.</td>
            <td >75</td>
        </tr>
        <tr>
            <td >2</td>
            <td >Демонтаж подвесных потолков (потолков из ГКЛ)</td>
            <td >кв.м.</td>
            <td >150</td>
        </tr>
        <tr>
            <td >3</td>
            <td >Демонтаж подвесных потолков (покрытий по обрешетке)</td>
            <td >кв.м.</td>
            <td >100</td>
        </tr>
        <tr>
            <td >4</td>
            <td >Демонтаж обрешетки</td>
            <td >кв.м.</td>
            <td >50</td>
        </tr>
        <tr>
            <td >5</td>
            <td >Зачистка от старого покрытия: обоев со смывкой</td>
            <td >кв.м.</td>
            <td >100</td>
        </tr>
        <tr>
            <td >6</td>
            <td >Зачистка от старого покрытия: побелки</td>
            <td >кв.м.</td>
            <td >100</td>
        </tr>
        <tr>
            <td >7</td>
            <td >Зачистка от старого покрытия: краски</td>
            <td >кв.м.</td>
            <td >200</td>
        </tr>
    </tbody>
</table>
<h3 class="table_variant_title">Монтажные работы</h3>
<table>
    <thead>
        <tr>
            <td class="column_1">№</td>
            <td class="column_2"  >Наименование работ</td>
            <td class="column_3"  >Ед.изм.</td>
            <td class="column_4 price"  >Стоимость работ (руб)*</td>
        </tr>
    </thead>
    <tbody>
    <tr></tr>
        <tr>
            <td >1</td>
            <td >Грунтовка потолка бетоноконтактом</td>
            <td >кв.м.</td>
            <td >75</td>
        </tr>
        <tr>
            <td >2</td>
            <td >Грунтовка черновая проникающими составами</td>
            <td >кв.м.</td>
            <td >25</td>
        </tr>
        <tr>
            <td >3</td>
            <td >Чистовая грунтовка</td>
            <td >кв.м.</td>
            <td >25</td>
        </tr>
        <tr>
            <td >4</td>
            <td >Устройство пароизоляции</td>
            <td >кв.м.</td>
            <td >75</td>
        </tr>
        <tr>
            <td >5</td>
            <td >Устройство тепло-звукоизоляции (слой)</td>
            <td >кв.м.</td>
            <td >150</td>
        </tr>
        <tr>
            <td >6</td>
            <td >Расшивка и заделка межплиточных швов</td>
            <td >п.м.</td>
            <td >150</td>
        </tr>
        <tr>
            <td >7</td>
            <td >Выравнивание примыканий потолка к стене</td>
            <td >п.м.</td>
            <td >150</td>
        </tr>
        <tr>
            <td >8</td>
            <td >Выравнивание потолка с использованием сухих смесей</td>
            <td >кв.м.</td>
            <td >500</td>
        </tr>
        <tr>
            <td >9</td>
            <td >Выравнивание потолка с использованием шлифования потолка</td>
            <td >кв.м.</td>
            <td >от 50</td>
        </tr>
        <tr>
            <td >10</td>
            <td >Шпаклёвка выравненых потолков под обои</td>
            <td >кв.м.</td>
            <td >200</td>
        </tr>
        <tr>
            <td >11</td>
            <td >Шпаклёвка выравненных потолков под покраску</td>
            <td >кв.м.</td>
            <td >300</td>
        </tr>
        <tr>
            <td >12</td>
            <td >Оклейка потолка стеклохолстом</td>
            <td >кв.м.</td>
            <td >150</td>
        </tr>
        <tr>
            <td >13</td>
            <td >оклейка торцов прямолинейных, криволинейных стеклохолстом</td>
            <td >п.м.</td>
            <td >100</td>
        </tr>
        <tr>
            <td >14</td>
            <td >Заделка швов ГКЛ серпянкой / бумагой с шпаклевкой</td>
            <td >п.м.</td>
            <td >50</td>
        </tr>
        <tr>
            <td >15</td>
            <td >Шпаклёвка торцов прямолинейных</td>
            <td >п.м.</td>
            <td >250</td>
        </tr>
        <tr>
            <td >16</td>
            <td >Шпаклёвка торцов криволинейных</td>
            <td >п.м.</td>
            <td >300</td>
        </tr>
        <tr>
            <td >17</td>
            <td >изготовление нестандартных подвесов</td>
            <td >шт.</td>
            <td >25</td>
        </tr>
        <tr>
            <td >18</td>
            <td >Устройство торцов из ГКЛ на м/к: прямолинейных</td>
            <td >м.п.</td>
            <td >250</td>
        </tr>
        <tr>
            <td >19</td>
            <td >Устройство торцов из ГКЛ на м/к: криволинейных</td>
            <td >п.м.</td>
            <td >350</td>
        </tr>
        <tr>
            <td >20</td>
            <td >Монтаж короба ГКЛ</td>
            <td >п.м.</td>
            <td >500</td>
        </tr>
        <tr>
            <td >21</td>
            <td >Оклейка потолка обоями</td>
            <td >кв.м.</td>
            <td >от 250</td>
        </tr>
        <tr>
            <td >22</td>
            <td >Наклейка обойного бордюра</td>
            <td >п.м.</td>
            <td >100</td>
        </tr>
        <tr>
            <td >23</td>
            <td >Окраска потолка В.Э. красками в один тон</td>
            <td >кв.м.</td>
            <td >200</td>
        </tr>
        <tr>
            <td >24</td>
            <td >Окраска потолка В.Э. красками разных тонов (граница цвета)</td>
            <td >м.п.</td>
            <td >200</td>
        </tr>
        <tr>
            <td >25</td>
            <td >Окраска торцов</td>
            <td >п.м.</td>
            <td >150</td>
        </tr>
        <tr>
            <td >26</td>
            <td >Монтаж галтелей</td>
            <td >м.п.</td>
            <td >100</td>
        </tr>
        <tr>
            <td >27</td>
            <td >Окраска галтелей в тон потолка</td>
            <td >м.п.</td>
            <td >50</td>
        </tr>
        <tr>
            <td >28</td>
            <td >Шпаклевка галтелей</td>
            <td >место</td>
            <td >50</td>
        </tr>
        <tr>
            <td >29</td>
            <td >Шпаклевка галтелей</td>
            <td >п.м.</td>
            <td >50</td>
        </tr>
        <tr>
            <td >30</td>
            <td >Окраска галтелей тоном отличным от потолка</td>
            <td >п.м.</td>
            <td >150</td>
        </tr>
        <tr>
            <td >31</td>
            <td >Окраска галтелей более 7 см.</td>
            <td >п.м.</td>
            <td >от 100</td>
        </tr>
        <tr>
            <td >32</td>
            <td >Монтаж галтелей шириной более 7 см.</td>
            <td >м.п.</td>
            <td >150</td>
        </tr>
        <tr>
            <td >33</td>
            <td >Монтаж полиуретановых галтелей</td>
            <td >м.п.</td>
            <td >200</td>
        </tr>
        <tr>
            <td >34</td>
            <td >Монтаж полиуретановых галтелей шириной более 7 см.</td>
            <td >м.п.</td>
            <td >250</td>
        </tr>
        <tr>
            <td >35</td>
            <td >Монтаж кассетного потолка</td>
            <td >кв.м.</td>
            <td >250</td>
        </tr>
        <tr>
            <td >36</td>
            <td >Монтаж реечного потолка</td>
            <td >кв.м.</td>
            <td >400</td>
        </tr>
        <tr>
            <td >37</td>
            <td >Монтаж пластиковых панелей</td>
            <td >кв.м.</td>
            <td >400</td>
        </tr>
        <tr>
            <td >38</td>
            <td >Устройство потолков из пенопластовой плитки (по готовому основанию)</td>
            <td >кв.м.</td>
            <td >100</td>
        </tr>
        <tr>
            <td >39</td>
            <td >Облицовка вагонкой с устройством каркаса</td>
            <td >кв.м.</td>
            <td >500</td>
        </tr>
        <tr>
            <td >40</td>
            <td >Обработка антисептиком</td>
            <td >кв.м.</td>
            <td >50</td>
        </tr>
        <tr>
            <td >41</td>
            <td >Подготовка вагонки под лакировку</td>
            <td >кв.м.</td>
            <td >200</td>
        </tr>
        <tr>
            <td >42</td>
            <td >Лакировка вагонки</td>
            <td >кв.м.</td>
            <td >250</td>
        </tr>
        <tr>
        <td >43</td>
        <td >Установка уголков</td>
        <td >м.п.</td>
        <td >100</td>
    </tr>
    <tr>
        <td >44</td>
        <td >Установка уголков (арочных)</td>
        <td >м.п.</td>
        <td >120</td>
    </tr>
    <tr>
        <td >45</td>
        <td >Монтаж декоративных элементов (ГКЛ,дерево, и т.д.)</td>
        <td >кв.м.</td>
        <td >договор</td>
    </tr>
    </tbody>
</table>

<h2 class="table_top_title" id="welding_work">Сварочные работы</h2>


<h3 class="table_variant_title">Монтажные работы</h3>
<table>
    <thead>
        <tr>
            <td class="column_1">№</td>
            <td class="column_2"  >Наименование работ</td>
            <td class="column_3"  >Ед.изм.</td>
            <td class="column_4"  >Стоимость работ (руб)*</td>
        </tr>
    </thead>
    <tbody>
    <tr class="tr_table">
        <td colspan="4" class="table_title"><h2>Сварные швы</h2></td>
    </tr>
    <tr>
        <td>1</td>
        <td>Шов по железу (точечный, стыковочный, прерывистый)</td>
        <td>за 1 см</td>
        <td>от 15</td>
    </tr>
    <tr>
        <td>2</td>
        <td>Шов по нержавеющей стали (точечный, стыковочный, прерывистый)</td>
        <td>за 1 см</td>
        <td>от 17,5</td>
    </tr>
    <tr>
        <td>3</td>
        <td>Шов по алюминию и его сплавам (точечный, стыковочный, прерывистый)</td>
        <td>за 1 см</td>
        <td>от 20</td>
    </tr>
    <tr class="tr_table">
        <td colspan="4" class="table_title"><h2>Виды работ</h2></td>
    </tr>
    <tr>
        <td>1</td>
        <td>Изготовление ворот</td>
        <td>-</td>
        <td>от 4000</td>
    </tr>
    <tr>
        <td>2</td>
        <td>Замена петель на воротах</td>
        <td>-</td>
        <td>от 1000</td>
    </tr>
    <tr>
        <td>3</td>
        <td>Устранение перекоса ворот или рамы</td>
        <td>-</td>
        <td>от 1500</td>
    </tr>
    <tr>
        <td>4</td>
        <td>Усиление ворот</td>
        <td>-</td>
        <td>от 1000</td>
    </tr>
    <tr>
        <td>5</td>
        <td>Врезка калитки</td>
        <td>-</td>
        <td>от 2500</td>
    </tr>
    <tr>
        <td>6</td>
        <td>Подрез ворот</td>
        <td>-</td>
        <td>от 1500</td>
    </tr>
    <tr>
        <td>7</td>
        <td>Различные работы с замками</td>
        <td>-</td>
        <td>от 500</td>
    </tr>
    <tr>
        <td>8</td>
        <td>Сварка труб (стык)</td>
        <td>шт</td>
        <td>от 100</td>
    </tr>
    <tr>
        <td>9</td>
        <td>Замена батарей или стояков</td>
        <td>-</td>
        <td>от 3500</td>
    </tr>
    <tr>
        <td>10</td>
        <td>Изготовление заборов (сетка рабица)</td>
        <td>п.м.</td>
        <td>от 750</td>
    </tr>
    <tr>
        <td>11</td>
        <td>Изготовление решеток и других ограждений</td>
        <td>п.м.</td>
        <td>от 500</td>
    </tr>
    <tr>
        <td>12</td>
        <td>Изготовление лестниц (наружных, технических)</td>
        <td>п.м.</td>
        <td>от 1000</td>
    </tr>
    <tr>
        <td>13</td>
        <td>Козырьки над входом</td>
        <td>кв.м.</td>
        <td>от 5000</td>
    </tr>
    <tr>
        <td>14</td>
        <td>Изготовление перил</td>
        <td>п.м.</td>
        <td>от 3000</td>
    </tr>
    </tbody>
</table>